wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1648742960
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      - 17
      4: 3.8.8
      5: 0.12.11
      8:
      - 5
amsgrad:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
batch_size_action_mod:
  desc: null
  value: 512
c_window_len:
  desc: null
  value: 0
collate_fn:
  desc: null
  value: Utils.Utils.my_collate_v2
constr_weight:
  desc: null
  value: 1
d_sampler:
  desc: null
  value: 1
epochs:
  desc: null
  value: 300
epochs_action_mod:
  desc: null
  value: 300
in_a_d:
  desc: null
  value: 125
in_d:
  desc: null
  value: 3
l_rate:
  desc: null
  value: 0.0005
len_window_o:
  desc: null
  value: null
load_trajectories:
  desc: null
  value: false
max_n_steps:
  desc: null
  value: 1
max_n_steps_action_mod:
  desc: null
  value: 10000
max_n_steps_episode:
  desc: null
  value: 200
n_of_trajectories:
  desc: null
  value: 100
obs_noise:
  desc: null
  value: false
out_d:
  desc: null
  value: 64
path_dataset:
  desc: null
  value: /home/lorenzo/Documenti/UPF/MDP_DIST/Data/dataset_FetchReach_disc.pt
path_model:
  desc: null
  value: /home/lorenzo/Documenti/UPF/MDP_DIST/Models/FetchReach_action_states_dictionary_disc
path_trajectory:
  desc: null
  value: /home/lorenzo/Documenti/UPF/MDP_DIST/Data/trajectory_FetchReach_disc.npy
percent_random_sample:
  desc: null
  value: 1
seed:
  desc: null
  value: 0
shuffle:
  desc: null
  value: true
ub_w_dist:
  desc: null
  value: 1
wandb_group:
  desc: null
  value: FetchReach
wandb_record:
  desc: null
  value: true
